//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestKafkaDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestKafkaDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.stanleyulili.com/git/how-to-install-git-bash-on-windows/.
        /// </summary>
        internal static string GitBashInstructions {
            get {
                return ResourceManager.GetString("GitBashInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://hadoan.medium.com/install-kafka-in-windows-10-by-chocolately-.
        /// </summary>
        internal static string InstallationInstructions {
            get {
                return ResourceManager.GetString("InstallationInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test-Group.
        /// </summary>
        internal static string KafkaGroupId {
            get {
                return ResourceManager.GetString("KafkaGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kafka.apache.org/quickstart.
        /// </summary>
        internal static string KafkaInstructions {
            get {
                return ResourceManager.GetString("KafkaInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost:9092.
        /// </summary>
        internal static string KafkaServerUri {
            get {
                return ResourceManager.GetString("KafkaServerUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations\Topics.json.
        /// </summary>
        internal static string TopicConfigurationFile {
            get {
                return ResourceManager.GetString("TopicConfigurationFile", resourceCulture);
            }
        }
    }
}
